import * as RNLocalize from 'react-native-localize'
import { getSecureItem } from './secureAccount'

export const SUPPORTED_CURRENCIES = [
  { label: 'USD', value: 'USD' },
  { label: 'AED', value: 'AED' },
  { label: 'ARS', value: 'ARS' },
  { label: 'AUD', value: 'AUD' },
  { label: 'BCH', value: 'BCH' },
  { label: 'BDT', value: 'BDT' },
  { label: 'BHD', value: 'BHD' },
  { label: 'BMD', value: 'BMD' },
  { label: 'BNB', value: 'BNB' },
  { label: 'BRL', value: 'BRL' },
  { label: 'BTC', value: 'BTC' },
  { label: 'CAD', value: 'CAD' },
  { label: 'CHF', value: 'CHF' },
  { label: 'CLP', value: 'CLP' },
  { label: 'CNY', value: 'CNY' },
  { label: 'CZK', value: 'CZK' },
  { label: 'DKK', value: 'DKK' },
  { label: 'DOT', value: 'DOT' },
  { label: 'EOS', value: 'EOS' },
  { label: 'ETH', value: 'ETH' },
  { label: 'EUR', value: 'EUR' },
  { label: 'GBP', value: 'GBP' },
  { label: 'HKD', value: 'HKD' },
  { label: 'HUF', value: 'HUF' },
  { label: 'IDR', value: 'IDR' },
  { label: 'ILS', value: 'ILS' },
  { label: 'INR', value: 'INR' },
  { label: 'JPY', value: 'JPY' },
  { label: 'KRW', value: 'KRW' },
  { label: 'KWD', value: 'KWD' },
  { label: 'LKR', value: 'LKR' },
  { label: 'LTC', value: 'LTC' },
  { label: 'MMK', value: 'MMK' },
  { label: 'MXN', value: 'MXN' },
  { label: 'MYR', value: 'MYR' },
  { label: 'NGN', value: 'NGN' },
  { label: 'NOK', value: 'NOK' },
  { label: 'NZD', value: 'NZD' },
  { label: 'PHP', value: 'PHP' },
  { label: 'PKR', value: 'PKR' },
  { label: 'PLN', value: 'PLN' },
  { label: 'RUB', value: 'RUB' },
  { label: 'SAR', value: 'SAR' },
  { label: 'SEK', value: 'SEK' },
  { label: 'SGD', value: 'SGD' },
  { label: 'THB', value: 'THB' },
  { label: 'TRY', value: 'TRY' },
  { label: 'TWD', value: 'TWD' },
  { label: 'UAH', value: 'UAH' },
  { label: 'VEF', value: 'VEF' },
  { label: 'VND', value: 'VND' },
  { label: 'XAG', value: 'XAG' },
  { label: 'XAU', value: 'XAU' },
  { label: 'XDR', value: 'XDR' },
  { label: 'XLM', value: 'XLM' },
  { label: 'XRP', value: 'XRP' },
  { label: 'YFI', value: 'YFI' },
  { label: 'ZAR', value: 'ZAR' },
] as { label: string; value: string }[]

export const getCurrencyForConversion = async (): Promise<string> => {
  const currency = await getSecureItem('currencyUsedForConversion')
  if (currency) return currency

  return RNLocalize.getCurrencies()[0] || 'USD'
}
